### ISSUE TITLE
the Vy-per can‘t download

### ISSUE THREAD

**Issue by wangjiaxuan666** [epischedda/ViR#1]
Hi，I find your workflow on the aticle. viR looks precise for find the virus genome insert human geonome.

but when I use the software, I find the input need a outfile of Vy-per.

but when i get the software from http://www.ikmbtmp.uni-kiel.de/pibase/vy-per/vyper.v0.3.5.tar.gz. it doesn't work

can you send me a vy-per to my email(poormouse@126.com), or can you recommend other software for Vir workflow？

thanks a lots
best wishes

**Comment by epischedda** [comment]
Hi, thank you for using ViR.
I checked the link in the Vy-PER ufficial page (https://www.ikmb.uni-kiel.de/vy-per/index.html), it is correct but unfortunately it doesn't work. I think could be better to contact the Vy-PER authors for this issue.
You can test any other software that works with paired-end reads and prepare the input file as descried in the README. I cannot suggest you a specific software because i tested very well just Vy-PER. 
Best,
Elisa
